# -*- coding: utf-8 -*-
"""
Created on Wed Dec 18 09:25:47 2019

@author: Lucia
"""

SweepsParams = {'name':'SweepsConfig',
                'type':'group',
                'children': ({'name': 'VgSweep',
                                    'type': 'group',
                                    'children': ({'name':'Vinit',
                                                  'type':'float',
                                                  'value':0,
                                                  'siPrefix':True,
                                                  'suffix':'V'},
                                                 {'name':'Vfinal',
                                                  'type':'float',
                                                  'value':-0.4,
                                                  'siPrefix':True,
                                                  'suffix':'V'},
                                                 {'name':'Vstep',
                                                  'type':'float',
                                                  'value':-0.01,
                                                  'siPrefix':True,
                                                  'suffix':'V'},)},
                           {'name': 'VdSweep',
                            'type': 'group',
                            'children': ({'name':'Vinit',
                                          'type':'float',
                                          'value':0.02,
                                          'siPrefix':True,
                                          'suffix':'V'},
                                         {'name':'Vfinal',
                                          'type':'float',
                                          'value':0.2,
                                          'siPrefix':True,
                                          'suffix':'V'},
                                         {'name':'Vstep',
                                          'type':'float',
                                          'value':0.01,
                                          'siPrefix':True,
                                          'suffix':'V'},)}, 
                           {'name': 'MaxSlope',
                            'title':'Maximum Slope',
                            'type': 'float',
                            'value': 1e-10},
                           {'name': 'TimeOut',
                            'title':'Max Time for Stabilization',
                            'type': 'int',
                            'value': 10,
                            'siPrefix': True,
                            'suffix': 's'},
                          )}